'use strict';
// Exercises actual local UI and services. Denies all generation/login/upload calls.
const {chromium}=require('../../runtime/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.WORKBENCH_VERIFY_URL||'http://127.0.0.1:8877';
const root=process.env.WORKBENCH_EVIDENCE_DIR||path.resolve(__dirname,'../run/workbench-verification-20261007/evidence');
const results=[],errors=[],blocked=[];
async function main(){
 const url=new URL(base);assert(['127.0.0.1','localhost'].includes(url.hostname),'Localhost only');
 const health=await(await fetch(base+'/health')).json();assert(/workbench-verification/.test(health.outputDir),'Refusing mutations outside isolated verification storage');
 fs.mkdirSync(root,{recursive:true});
 // Reset only annotations within the explicitly isolated verification root.
 const initialAssets=await(await fetch(base+'/control/assets')).json();
 for(const a of initialAssets.items)await fetch(base+'/control/assets/'+a.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({favorite:false,archived:false,tags:[]})});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());
   if(u.origin!==url.origin){blocked.push(req.url());return route.abort();}
   if(req.method()!=='GET'&&!(/^\/control\/batches(?:\/validate)?$/.test(u.pathname)||/^\/control\/assets\/[a-f0-9]+$/.test(u.pathname))){blocked.push(req.method()+' '+u.pathname);return route.abort();}
   return route.continue();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const shot=async name=>page.screenshot({path:path.join(root,name+'.png'),fullPage:true});
 const count=async n=>assert.equal(await page.locator('#draft-table tbody tr').count(),n);
 const close=async()=>page.locator('#modal-close').click();
 const step=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('PASS '+name);};
 await page.goto(base+'/control');await page.locator('.connection.online').waitFor();
 await step('first-use',async()=>{assert.match(await page.locator('#draft-table').innerText(),/从第一条创意/);await shot('01-first-use');});
 await step('composer-and-inline',async()=>{await page.locator('#prompt-input').fill('A quiet forest at dawn, cinematic natural light');await page.locator('#task-name').fill('晨光森林');await page.locator('#default-aspect').selectOption('9:16');await page.locator('#advanced-params').evaluate(e=>e.open=true);await page.locator('#param-stylize').fill('300');await page.locator('#add-task').click();await count(1);await page.locator('[data-edit=name]').fill('晨光森林 · 第一轮');await page.locator('[data-edit=name]').blur();});
 await step('csv-import',async()=>{await page.locator('#import-batch').click();await page.locator('#import-format').selectOption('csv');await page.locator('#import-text').fill('name,prompt,aspect,version,seed\n夜景,"City at night, neon reflections",16:9,v7,42\n静物,Minimal ceramic vase,1:1,v8.2,43');await page.locator('#apply-import').click();await count(3);});
 await step('invalid-csv-raw-keeps-draft',async()=>{await page.locator('#import-batch').click();await page.locator('#import-format').selectOption('csv');await page.locator('#import-text').fill('prompt,raw\nA scene,maybe');await page.locator('#apply-import').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('raw 列只接受'));await count(3);await close();});
 await step('bulk-parameters-copy-remove',async()=>{await page.locator('#select-all').check();await page.locator('[data-bulk=settings]').click();await page.locator('#bulk-chaos').fill('15');await page.locator('#apply-params').click();await page.locator('[data-bulk=duplicate]').click();await count(6);await page.locator('[data-bulk=delete]').click();await count(3);});
 await step('combination-experiment',async()=>{await page.locator('#experiment-button').click();await page.locator('#experiment-s').fill('100, 400');await page.locator('#experiment-c').fill('0, 25');assert.match(await page.locator('#experiment-count').innerText(),/12 个任务/);await page.locator('#apply-experiment').click();await count(12);await page.locator('#batch-name').fill('本地验收 · 参数组合 · 不提交');await shot('02-batch-edit');});
 await step('templates-and-draft-reload',async()=>{await page.locator('#save-template').click();await page.locator('#template-name').fill('本地验收模板');await page.locator('#apply-template').click();await page.locator('#prompt-input').fill('未加入的创意保留');await page.locator('#param-seed').fill('123');await page.reload();await page.locator('.connection.online').waitFor();await count(12);assert.equal(await page.locator('#prompt-input').inputValue(),'未加入的创意保留');await page.locator('#advanced-params').evaluate(e=>e.open=true);assert.equal(await page.locator('#param-seed').inputValue(),'123');await page.locator('#templates-button').click();assert.match(await page.locator('#modal-body').innerText(),/本地验收模板/);await close();});
 await step('validate-save-without-dispatch',async()=>{await page.locator('#check-batch').click();await page.locator('#save-checked').waitFor();assert.equal(await page.locator('#save-checked').isEnabled(),true,await page.locator('#modal-body').innerText());await page.locator('#save-checked').click();await page.locator('[data-batch-action=start]').waitFor();assert.match(await page.locator('#batch-detail').innerText(),/实际单路/);await shot('05-real-saved-queue');const batches=await(await fetch(base+'/control/batches')).json();const saved=batches.items.find(b=>b.name==='本地验收 · 参数组合 · 不提交');assert(saved);const batch=await(await fetch(base+'/control/batches/'+saved.batchId)).json();assert.equal(batch.status,'validated');assert(batch.items.every(i=>!i.currentJobId&&i.attempts===0));fs.writeFileSync(path.join(root,'saved-batch.json'),JSON.stringify({batchId:saved.batchId,status:batch.status,count:batch.items.length},null,2));});
 await step('latest-batch-entry-does-not-submit',async()=>{await page.goto(base+'/control?focus=latest');await page.locator('.connection.online').waitFor();await page.locator('[data-batch-action=start]').waitFor();assert.equal(await page.locator('#queue-view').isVisible(),true);await page.locator('[data-view=prepare]').click();await page.evaluate(()=>window.MulticaWorkbench.openLatestBatch());assert.equal(await page.locator('#queue-view').isVisible(),true);});
 await step('paid-confirmation-is-locked',async()=>{await page.locator('[data-batch-action=start]').click();assert.equal(await page.locator('#confirm-action').isEnabled(),false);assert.equal(await page.locator('#confirm-paid').isChecked(),false);await shot('06-confirmation-not-authorized');await close();});
 await step('real-gallery-images',async()=>{await page.locator('[data-view=gallery]').click();await page.locator('.asset-card').first().waitFor();assert.equal(await page.locator('.asset-card').count(),8);await page.locator('.asset-preview img').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));assert(await page.locator('.asset-preview img').evaluateAll(imgs=>imgs.every(i=>i.naturalWidth>0)));await shot('03-gallery');});
 let assetId;
 await step('preview-tags-favorite-archive',async()=>{assetId=await page.locator('[data-preview]').first().getAttribute('data-preview');await page.locator('[data-preview]').first().click();assert(!(await page.locator('#modal-body').innerText()).includes('[object Object]'));assert.equal(await page.locator('#reuse-asset').isEnabled(),false);await page.locator('#preview-tags').fill('验收标注, 待选');await page.locator('#preview-save-tags').click();await page.waitForFunction(()=>!document.body.classList.contains('working'));await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('已保存'));await page.locator('#preview-favorite').click();await page.waitForFunction(()=>document.querySelector('#preview-favorite').textContent.includes('已收藏'));await shot('04-preview');await page.locator('#preview-archive').click();await page.waitForFunction(()=>document.querySelector('#preview-archive').textContent.includes('取消归档'));await close();assert.equal(await page.locator('.asset-card').count(),7);await page.locator('#gallery-filter').selectOption('archived');assert.equal(await page.locator('.asset-card').count(),1);await page.locator('#gallery-search').fill('验收标注');assert.equal(await page.locator('.asset-card').count(),1);await page.locator('[data-preview]').click();await page.locator('#preview-archive').click();await page.waitForFunction(()=>document.querySelector('#preview-archive').textContent.trim()==='归档');await close();await page.locator('#gallery-search').fill('');await page.locator('#gallery-filter').selectOption('favorite');assert.equal(await page.locator('.asset-card').count(),1);await page.locator('#gallery-filter').selectOption('active');});
 await step('comparison-and-keyboard',async()=>{await page.locator('[data-compare]').nth(0).check();await page.locator('[data-compare]').nth(1).check();await page.locator('#compare-button').click();assert.equal(await page.locator('.compare-grid img').count(),2);await shot('07-compare');await page.keyboard.press('Escape');await page.locator('[data-preview]').first().click();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#modal').evaluate(e=>e.open),true);await page.keyboard.press('Escape');});
 await step('dialog-tab-focus-and-escape',async()=>{await page.locator('[data-preview]').first().click();for(let i=0;i<18;i++){await page.keyboard.press('Tab');assert(await page.locator('#modal').evaluate(e=>e.contains(document.activeElement)),'Tab focus escaped native dialog');}await page.keyboard.press('Escape');assert.equal(await page.locator('#modal').evaluate(e=>e.open),false);});
 await step('annotation-persists-across-client-reload',async()=>{await page.reload();await page.locator('.connection.online').waitFor();await page.locator('[data-view=gallery]').click();await page.locator('.asset-card').first().waitFor();await page.locator('#gallery-filter').selectOption('favorite');assert.equal(await page.locator('.asset-card').count(),1);const assets=await(await fetch(base+'/control/assets')).json();assert(assets.items.find(a=>a.id===assetId).tags.includes('验收标注'));fs.writeFileSync(path.join(root,'annotation-check.json'),JSON.stringify({id:assetId,tags:['验收标注','待选'],favorite:true},null,2));});
 await step('responsive-layout',async()=>{for(const width of [1440,900,600,390]){await page.setViewportSize({width,height:1000});for(const view of ['prepare','queue','gallery','settings']){await page.locator('[data-view='+view+']').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow: '+width+' '+view);}if(width===390){await page.locator('[data-view=prepare]').click();assert(await page.locator('#import-batch').isVisible());await shot('08-narrow-window');}}});
 await step('offline-draft-stays-editable',async()=>{await page.route('**/control/state',route=>route.abort());await page.locator('[data-view=prepare]').click();await page.locator('#refresh-button').click();await page.locator('.connection.offline').waitFor();assert.equal(await page.locator('#check-batch').isEnabled(),false);await page.locator('#prompt-input').fill('离线时仍可准备');await shot('09-offline');await page.unroute('**/control/state');});
 await step('corrupt-storage-is-backed-up',async()=>{await page.evaluate(()=>localStorage.setItem('multica-workbench-v2','{broken'));await page.reload();await page.locator('.connection.online').waitFor();assert(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('multica-workbench-v2.unreadable-')&&localStorage.getItem(k)==='{broken')));assert.match(await page.locator('#toast').innerText(),/原文已另存备份/);});
 // Local DOM contract only; never navigates to the paid platform.
 await step('adapter-model-family-and-async-selection',async()=>{const Adapter=require('./mxai_adapter.js');const dom=await context.newPage();const adapter=Object.create(Adapter.prototype);adapter.page=dom;await dom.setContent('<div class="mj-left-tool"><button id="family">Midjourney</button><div id="chips"></div></div>');await dom.evaluate(()=>{document.querySelector('#family').onclick=()=>setTimeout(()=>{document.querySelector('#chips').innerHTML='<button class="tile-selector-item">NJ7.0</button><button class="tile-selector-item" id="v7">v7.0</button>';document.querySelector('#v7').onclick=e=>setTimeout(()=>e.target.classList.add('is-selected'),150);},150);});await adapter.selectVersion('v7');assert(adapter._lastVersion.verified);await dom.setContent('<div class="mj-left-tool"><button id="family">Mid`J</button><button class="tile-selector-item is-selected" id="v82">v8.2</button><button class="tile-selector-item">v6.1</button></div>');await dom.evaluate(()=>{document.querySelector('#family').onclick=()=>document.querySelectorAll('.tile-selector-item').forEach(e=>e.remove());});await adapter.selectVersion('v8.2');assert(adapter._lastVersion.verified);assert.equal(await dom.locator('.tile-selector-item').count(),2,'Visible model chips must not be closed by toggling the family title');await dom.setContent('<div class="mj-left-tool"><button>Midjourney</button><button class="tile-selector-item is-selected">NJ7.0</button></div>');await assert.rejects(()=>adapter.selectVersion('v7'),e=>e.code==='VERSION_NOT_APPLIED');await dom.close();});
 assert.equal(errors.length,0);assert.equal(blocked.length,0,'Unexpected external or prohibited mutation');
 fs.writeFileSync(path.join(root,'ui-verification.json'),JSON.stringify({date:new Date().toISOString(),base,results,errors,blocked,realImageCount:8,paidGenerationExecuted:false},null,2));
 console.log('UI PASS '+results.length+' checks; real images=8; paid calls=0');
 }finally{await browser.close();}
}
main().catch(e=>{fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'ui-failure.json'),JSON.stringify({results,errors,blocked,error:String(e)},null,2));console.error(e);process.exitCode=1;});
