'use strict';
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ASPECTS=['16:9','9:16','1:1','4:3','3:4','3:2','2:3','1:2'], VERSIONS=['v8.2','v8.1','v7','v6.1','v6','niji7','niji6'];
const LABEL={validated:'待确认',running:'运行中',paused:'已暂停',completed:'已完成',cancelled:'已取消',pending:'本地排队',failed:'异常',result_pending:'待核查',login_required:'需要登录',skipped:'已跳过'};
const PHASE={browser_wait:'等待浏览器锁',preparing:'浏览器准备中',submitting:'提交结果待确认',platform_generating:'平台生成中',downloading:'下载与校验中',completed:'成品已保存',result_pending:'回执待核查'};
function taskPhaseLabel(row,job){if(row.status==='login_required')return LABEL.login_required;if(row.status==='skipped')return job.resultStatus==='page_reported_failed'?'已跳过 · 平台生成失败':LABEL.skipped;if(job.resultStatus==='page_reported_failed')return '平台生成失败';return PHASE[job.phase]||LABEL[row.status]||row.status;}
const emptyDraft=()=>({name:'',items:[],outputDir:'',profileMode:'shared',concurrency:3});
const S={draft:emptyDraft(),selected:new Set(),templates:[],view:'prepare',queueFilter:'all',queueSearch:'',queueComposing:false,bridge:null,batch:null,batchId:'',assets:[],assetSelection:new Set(),storage:null,compare:new Set(),previewId:null,refreshBusy:false,busy:false,jobFilter:null,focusLatest:new URLSearchParams(location.search).get('focus')==='latest'};
const storageBlocked=new Set();let storageNotice='';
function readStored(key,fallback,valid){try{const raw=localStorage.getItem(key);if(!raw)return fallback;try{const value=JSON.parse(raw);if(!valid(value))throw Error('invalid stored structure');return value;}catch{try{localStorage.setItem(key+'.unreadable-'+Date.now(),raw);storageNotice='发现损坏的本地草稿或模板，原文已另存备份；可重新编辑。';}catch{storageBlocked.add(key);storageNotice='本地数据无法读取或备份，已停止覆盖；请先导出并检查浏览器存储。';}return fallback;}}catch{storageBlocked.add(key);storageNotice='浏览器存储不可用，请及时导出草稿。';return fallback;}}
function store(key,value){if(storageBlocked.has(key))throw Error('原本地数据尚未备份，已停止覆盖');localStorage.setItem(key,JSON.stringify(value));}
const validItem=r=>r&&typeof r.prompt==='string'&&typeof r.id==='string'&&r.params&&typeof r.params==='object'&&!Array.isArray(r.params);
const savedDraft=readStored('multica-workbench-v2',null,d=>d&&Array.isArray(d.items)&&d.items.length<=500&&d.items.every(validItem));if(savedDraft)S.draft={...emptyDraft(),...savedDraft};
S.loginReminder=readStored('multica-login-reminder-v1',true,v=>typeof v==='boolean');
S.loginSeen=new Set(readStored('multica-login-seen-v1',[],v=>Array.isArray(v)&&v.every(k=>typeof k==='string')));
S.loginAlerts=[];
S.templates=readStored('multica-templates-v2',[],t=>Array.isArray(t)&&t.every(r=>r&&typeof r.name==='string'&&Array.isArray(r.items)&&r.items.every(validItem)));
try{S.batchId=localStorage.getItem('multica-batch-v2')||'';}catch{}
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function persist(){try{store('multica-workbench-v2',S.draft);$('draft-saved').textContent='草稿已自动保存 · '+new Date().toLocaleTimeString('zh-CN');}catch{toast('浏览器存储不可用，请导出草稿备份。');}}
async function api(url,method='GET',body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{method,signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data));return data;}catch(e){if(e.name==='AbortError')throw Error('本地服务响应超时。状态未确认，请先刷新，不要重复提交。');throw e;}finally{clearTimeout(timer);}}
async function guarded(fn){if(S.busy)return;S.busy=true;document.body.classList.add('working');try{await fn();}catch(e){toast(e.message||String(e));}finally{S.busy=false;document.body.classList.remove('working');maybeShowLoginReminder();}}
function dialog(title,body){$('modal').classList.remove('preview-modal');$('modal-body').onclick=null;S.previewId=null;$('modal-title').textContent=title;$('modal-body').innerHTML=body;if(!$('modal').open)$('modal').showModal();}
function closeDialog(){$('modal').close();S.previewId=null;}
// Only an explicit, unsubmitted login failure can summon a person. Unknown receipts stay under review.
function collectLoginAlerts(batches){
 const alerts=[];
 for(const b of batches){
  if(b.status==='cancelled')continue;
  for(const row of b.items||[]){
   const job=row.liveJob||row.lastResult||{};
   if(row.status!=='login_required'||job.submitted!==false)continue;
   const key=JSON.stringify([b.batchId,row.id,row.currentJobId||row.submissionId||null,row.attempts||0]);
   alerts.push({key,batchId:b.batchId,itemId:row.id,batchName:b.name||b.batchId,taskName:row.name||row.id,slot:row.slot,profileMode:b.profileMode,profileKey:row.profile||JSON.stringify([b.batchId,row.slot])});
  }
 }
 return alerts;
}
function loginReminderCandidate(alerts,seen,enabled,modalOpen,busy){return enabled&&!modalOpen&&!busy?alerts.find(a=>!seen.has(a.key)):undefined;}
function loginSnapshotReady(result){return result.loggedIn===true||result.loginState==='logged_in';}
async function updateLoginAlerts(state){
 const candidates=(state.batches||[]).filter(b=>b.counts?.login_required>0&&b.status!=='cancelled');
 const details=await Promise.allSettled(candidates.map(b=>b.batchId===S.batch?.batchId?S.batch:api('/control/batches/'+encodeURIComponent(b.batchId))));
 S.loginAlerts=collectLoginAlerts(details.filter(r=>r.status==='fulfilled').map(r=>r.value));
}
function maybeShowLoginReminder(force=false){
 if(!S.bridge)return;
 const target=loginReminderCandidate(S.loginAlerts,force?new Set():S.loginSeen,force||S.loginReminder,$('modal').open,S.busy);
 if(!target)return;
 const related=S.loginAlerts.filter(a=>a.profileKey===target.profileKey);
 for(const a of related)S.loginSeen.add(a.key);
 const activeKeys=new Set(S.loginAlerts.map(a=>a.key));
 S.loginSeen=new Set([...S.loginSeen].filter(k=>!activeKeys.has(k)).slice(-100).concat([...S.loginSeen].filter(k=>activeKeys.has(k))));
 try{store('multica-login-seen-v1',[...S.loginSeen]);}catch{toast('提醒已显示；浏览器存储不可用，重新打开工作台时可能再次提醒。');}
 dialog('需要你帮忙登录',`<div class="alert">检测到未登录，相关批次已暂停派发。</div><p><strong>${esc(target.batchName)}</strong> · ${esc(target.taskName)}</p><p>${target.profileMode==='shared'?'共享浏览器档案':'独立工作位 '+esc(target.slot??'缺')} · ${related.length} 项待登录处理</p><p class="hint">上述任务回执明确记录尚未提交。打开对应窗口后请手动登录，再回来核查。登录核查不会提交生成。</p><p id="login-reminder-status" role="status" aria-live="polite"></p><div class="modal-actions"><button id="login-reminder-open" class="button primary">打开登录窗口</button><button id="login-reminder-check" class="button">登录后重新检查</button><button id="login-reminder-batch" class="button">查看待登录批次</button><button id="login-reminder-later" class="text-button">稍后处理</button></div>`);
 const endpoint='/control/batches/'+encodeURIComponent(target.batchId)+'/items/'+encodeURIComponent(target.itemId)+'/login';
 const loginAction=method=>guarded(async()=>{
  const status=$('login-reminder-status');
  status.textContent=method==='POST'?'正在打开对应登录窗口…':'正在核查登录状态…';
  try{
   const result=await api(endpoint,method,method==='POST'?{}:undefined);
   // The dialog may have been closed while the request was pending. Do not overwrite a new dialog.
   if($('login-reminder-status')!==status)return;
   status.textContent=method==='POST'?(result.message||'窗口已打开，请手动登录。'):loginSnapshotReady(result)?'登录已核验。请查看批次，确认本次费用后继续生成。':'尚未核验到登录，请在对应窗口完成登录后再次检查。';
  }catch(e){if($('login-reminder-status')===status)status.textContent=e.message;}
 });
 $('login-reminder-open').onclick=()=>loginAction('POST');
 $('login-reminder-check').onclick=()=>loginAction('GET');
 $('login-reminder-batch').onclick=()=>guarded(async()=>{S.batchId=target.batchId;S.queueFilter='all';S.queueSearch='';localStorage.setItem('multica-batch-v2',S.batchId);closeDialog();switchView('queue');await refresh();});
 $('login-reminder-later').onclick=closeDialog;
}
function options(values,value,blank=false){return (!blank&&value&&!values.includes(value)?`<option selected value="${esc(value)}">不支持：${esc(value)}</option>`:'')+(blank?'<option value="">保持原值</option>':'')+values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('');}
function id(){return 'task-'+crypto.randomUUID().slice(0,12);}
function copyItem(row){return {id:id(),name:row.name||'未命名任务',prompt:row.prompt||'',aspect:(typeof row.requestedAspect==='string'?row.requestedAspect:typeof row.aspect==='string'?row.aspect:row.aspect?.requested)||'16:9',version:row.version||'v8.2',params:{...(row.params||{})}};}
function addItems(rows){if(S.draft.items.length+rows.length>500)throw Error('一轮最多 500 个任务，请拆分批次。');S.draft.items.push(...rows);persist();renderDraft();}
function switchView(view){S.view=view;for(const v of ['prepare','queue','gallery','settings'])$(v+'-view').hidden=v!==view;document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('view-name').textContent={prepare:'准备创意',queue:'运行与批次',gallery:'图片工作区',settings:'连接与设置'}[view];if(view==='gallery')loadAssets().catch(e=>toast(e.message));if(view==='queue')renderQueue();if(view==='settings'){renderSettings();loadStorage().then(renderSettings).catch(e=>toast(e.message));}}
function paramsFrom(prefix='param-'){const p={};for(const key of ['stylize','chaos','seed','quality']){const value=$(prefix+key).value;if(value!=='')p[key]=Number(value);}if($(prefix+'raw').checked)p.raw=true;return p;}
function renderDraft(){const rows=S.draft.items;$('draft-count').textContent=rows.length;$('selection-count').textContent=S.selected.size?`已选 ${S.selected.size} 项`:'未选择';$('select-all').checked=rows.length>0&&rows.every(r=>S.selected.has(r.id));$('check-batch').disabled=!rows.length||!S.bridge;
$('draft-table').innerHTML=rows.length?`<div class="table-scroll"><table class="draft-table"><thead><tr><th>选择</th><th>名称 / 提示词</th><th>画幅</th><th>版本</th><th>参数</th><th>操作</th></tr></thead><tbody>${rows.map((r,n)=>`<tr data-id="${esc(r.id)}"><td><input type="checkbox" data-edit="selected" aria-label="选择任务 ${n+1}" ${S.selected.has(r.id)?'checked':''}></td><td><input data-edit="name" aria-label="任务名称" value="${esc(r.name)}"><textarea data-edit="prompt" aria-label="任务提示词" rows="2">${esc(r.prompt)}</textarea></td><td><select data-edit="aspect" aria-label="任务画幅">${options(ASPECTS,r.aspect)}</select></td><td><select data-edit="version" aria-label="任务版本">${options(VERSIONS,r.version)}</select></td><td><button class="button small" data-row="params">${Object.keys(r.params||{}).length?esc(Object.entries(r.params).map(([k,v])=>k+' '+v).join(' · ')):'默认参数'}</button></td><td><button class="text-button" data-row="copy">复制</button><button class="text-button danger" data-row="remove">移除</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state"><div class="empty-icon">＋</div><h3>从第一条创意开始</h3><p>在上方输入提示词，或批量导入已有创意。草稿不会触发生成。</p></div>';
for(const el of document.querySelectorAll('[data-bulk]'))el.disabled=!S.selected.size;}
function exportJSON(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openParams(ids){const single=ids.length===1?S.draft.items.find(r=>r.id===ids[0]):null,p=single?.params||{};dialog(single?'编辑任务参数':'批量调整参数',`<p class="hint">空白保持原值。修改草稿不会提交。</p><div class="field-grid"><label>画幅<select id="bulk-aspect">${options(ASPECTS,single?.aspect,true)}</select></label><label>版本<select id="bulk-version">${options(VERSIONS,single?.version,true)}</select></label>${['stylize','chaos','seed','quality'].map(k=>`<label>${{stylize:'风格化',chaos:'变化幅度',seed:'种子',quality:'质量'}[k]}<input id="bulk-${k}" type="number" value="${esc(p[k]??'')}" placeholder="保持原值"></label>`).join('')}<label>Raw<select id="bulk-raw"><option value="">保持原值</option><option value="true">开启</option><option value="false">关闭</option></select></label></div><label class="checkbox-label"><input id="bulk-clear" type="checkbox">先清空高级参数，再应用填写值</label><div class="modal-actions"><button id="apply-params" class="button primary">应用到 ${ids.length} 个任务</button></div>`);$('apply-params').onclick=()=>guarded(async()=>{for(const row of S.draft.items.filter(r=>ids.includes(r.id))){if($('bulk-clear').checked)row.params={};for(const k of ['aspect','version'])if($('bulk-'+k).value)row[k]=$('bulk-'+k).value;for(const k of ['stylize','chaos','seed','quality'])if($('bulk-'+k).value!=='')row.params[k]=Number($('bulk-'+k).value);if($('bulk-raw').value)row.params.raw=$('bulk-raw').value==='true';}persist();renderDraft();closeDialog();toast('参数已应用。保存前将检查兼容性。');});}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(cell.trim());cell='';if(c==='\n'){if(row.some(Boolean))rows.push(row);row=[];}}else if(c!=='\r'||quoted)cell+=c;}if(quoted)throw Error('CSV 引号未闭合');row.push(cell.trim());if(row.some(Boolean))rows.push(row);const header=rows.shift()?.map(v=>v.toLowerCase());if(!header?.includes('prompt'))throw Error('CSV 首行需要 prompt 列，可选 name、aspect、version、stylize、chaos、seed、quality、raw。');return rows.map(values=>{const r=Object.fromEntries(header.map((h,i)=>[h,values[i]||'']));r.params={};for(const k of ['stylize','chaos','seed','quality'])if(r[k]!=null&&r[k]!=='')r.params[k]=Number(r[k]);if(r.raw){if(!['true','false'].includes(r.raw.toLowerCase()))throw Error('CSV 的 raw 列只接受 true、false 或空白');r.params.raw=r.raw.toLowerCase()==='true';}return r;});}
function importDialog(){dialog('批量导入创意',`<p>纯文本每行一条，或导入 JSON、JSONL、CSV。文件只在本机读取，不上传。</p><label>选择文件<input id="import-file" type="file" accept=".txt,.json,.jsonl,.csv"></label><label>导入格式<select id="import-format"><option value="text">每行一条提示词</option><option value="json">JSON 批次 / 任务数组</option><option value="jsonl">JSONL 每行一项</option><option value="csv">CSV（含 prompt 列）</option></select></label><textarea id="import-text" rows="9" placeholder="粘贴提示词，或从文件读取"></textarea><div class="modal-actions"><button id="apply-import" class="button primary">加入当前草稿</button></div>`);$('import-file').onchange=()=>guarded(async()=>{const f=$('import-file').files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('文件最多 2 MB。');$('import-text').value=await f.text();$('import-format').value=({json:'json',jsonl:'jsonl',csv:'csv'})[f.name.split('.').pop().toLowerCase()]||'text';});$('apply-import').onclick=()=>guarded(async()=>{const text=$('import-text').value.trim();if(!text)throw Error('请先填写创意');let rows;switch($('import-format').value){case 'json':{const p=JSON.parse(text);rows=Array.isArray(p)?p:p.items||p.tasks;break;}case 'jsonl':rows=text.split(/\r?\n/).filter(Boolean).map(v=>JSON.parse(v));break;case 'csv':rows=parseCSV(text);break;default:rows=text.split(/\r?\n/).filter(v=>v.trim()).map(prompt=>({prompt,aspect:$('default-aspect').value,version:$('default-version').value}));}if(!Array.isArray(rows)||rows.some(r=>!r||typeof r.prompt!=='string'||!r.prompt.trim()))throw Error('每个任务都需要非空 prompt 字段');addItems(rows.map((r,n)=>({...copyItem(r),name:r.name||'导入创意 '+(n+1)})));closeDialog();toast(`已导入 ${rows.length} 个任务，尚未提交。`);});}
function experimentDialog(){const rows=S.draft.items.filter(r=>!S.selected.size||S.selected.has(r.id));if(!rows.length)return toast('先加入一些任务');dialog('参数组合实验',`<p>将 ${rows.length} 条创意展开为参数组合，替换选中的原任务。只修改草稿。</p><div class="field-grid"><label>风格化列表<input id="experiment-s" value="100, 300, 600"></label><label>变化幅度列表<input id="experiment-c" value="0, 25"></label></div><p id="experiment-count" class="alert"></p><div class="modal-actions"><button id="apply-experiment" class="button primary">展开组合</button></div>`);const read=()=>{const parse=(s,max)=>{const a=[...new Set(s.split(/[,，\s]+/).filter(Boolean).map(Number))];if(!a.length||a.some(v=>!Number.isInteger(v)||v<0||v>max))throw Error('请使用范围内的整数，以逗号分隔');return a;};const a=parse($('experiment-s').value,1000),b=parse($('experiment-c').value,100);return {a,b,count:rows.length*a.length*b.length+S.draft.items.length-rows.length};};const preview=()=>{try{const v=read();$('experiment-count').textContent=`${rows.length} 条创意 × ${v.a.length} 种风格 × ${v.b.length} 种变化 → 本轮 ${v.count} 个任务`;$('apply-experiment').disabled=v.count>500;}catch(e){$('experiment-count').textContent=e.message;$('apply-experiment').disabled=true;}};for(const el of [$('experiment-s'),$('experiment-c')])el.oninput=preview;preview();$('apply-experiment').onclick=()=>guarded(async()=>{const {a,b,count}=read();if(count>500)throw Error('本轮最多 500 项');const selected=new Set(rows.map(r=>r.id)),expanded=[];for(const r of S.draft.items){if(!selected.has(r.id)){expanded.push(r);continue;}for(const stylize of a)for(const chaos of b)expanded.push({...copyItem(r),name:`${r.name} · S${stylize} C${chaos}`,params:{...r.params,stylize,chaos}});}S.draft.items=expanded;S.selected.clear();persist();renderDraft();closeDialog();toast('组合已展开，可逐项编辑后检查。');});}
function templatesDialog(){dialog('我的创作模板',`<p class="hint">模板保存在当前浏览器；导出草稿可跨窗口迁移。</p>${S.templates.length?S.templates.map((t,i)=>`<div class="template-row"><div><strong>${esc(t.name)}</strong><p>${t.items.length} 个任务</p></div><button class="button" data-template="${i}">加入草稿</button><button class="text-button danger" data-template-delete="${i}">删除</button></div>`).join(''):'<div class="empty-state"><h3>还没有模板</h3><p>将本轮任务存为模板，让一次准备服务多轮创作。</p></div>'}`);$('modal-body').onclick=e=>{const add=e.target.closest('[data-template]'),del=e.target.closest('[data-template-delete]');if(add)guarded(async()=>{addItems(S.templates[Number(add.dataset.template)].items.map(copyItem));closeDialog();});if(del)guarded(async()=>{const next=S.templates.filter((_,i)=>i!==Number(del.dataset.templateDelete));store('multica-templates-v2',next);S.templates=next;templatesDialog();});};}
async function checkBatch(){await loadStorage();if(!S.bridge)throw Error('本地服务离线，仍可编辑和导出草稿。');const payload={...S.draft,batchId:'batch-'+crypto.randomUUID().slice(0,12),name:S.draft.name||'创作 '+new Date().toLocaleString('zh-CN'),outputDir:S.draft.outputDir||S.storage?.outputDir||S.bridge.health?.outputDir||S.bridge.health?.resultsDir};if(!payload.outputDir)delete payload.outputDir;const result=await api('/control/batches/validate','POST',payload);dialog('提交前检查 · 保存不生成',`<div class="alert ${result.ok?'success':'danger'}">${result.ok?'检查通过，可以保存为待确认批次。':'请修正以下问题后再保存。'}</div>${[...(result.errors||[]),...(result.warnings||[])].map(r=>`<p>${esc(r.item||r.field)} · ${esc(r.message)}</p>`).join('')}<p>${S.draft.items.length} 个任务 · ${S.draft.profileMode==='shared'?'共享档案，实际单路':'独立档案，最多 '+S.draft.concurrency+' 路'}</p><p class="hint">实际费用：缺。保存不会触发付费生成。平台参数采用情况尚未核验。</p><div class="modal-actions"><button id="save-checked" class="button primary" ${!result.ok?'disabled':''}>保存批次，暂不提交</button></div>`);$('save-checked').onclick=()=>guarded(async()=>{const saved=await api('/control/batches','POST',result.normalized);S.batchId=saved.batchId;localStorage.setItem('multica-batch-v2',S.batchId);closeDialog();await refresh();switchView('queue');toast('批次已保存。开始生成前，还需你明确确认。');});}
const QUEUE_FILTERS={all:'全部',attention:'需要处理',pending:'排队',running:'运行中',completed:'成品',skipped:'已跳过'};
function queueGroup(row){if(['completed','skipped','pending','running'].includes(row.status))return row.status;return 'attention';}
function queueRows(items,filter,search){const query=search.trim().toLocaleLowerCase();return items.filter(row=>{const job=row.liveJob||row.lastResult||{};return (filter==='all'||queueGroup(row)===filter)&&(!query||[row.name,row.prompt,row.currentJobId,job.recordId,job.serial,row.failureReason,job.message].filter(Boolean).join(' ').toLocaleLowerCase().includes(query));});}
function queueGuidance(row){const job=row.liveJob||row.lastResult||{};if(queueGroup(row)!=='attention')return '';if(row.status==='login_required'&&job.submitted===false)return '先打开对应窗口手动登录，再核对登录。确认未提交后重试，最后确认继续批次。';if(job.resultStatus==='page_reported_failed')return '平台已返回生成失败。请保留回执并核对平台退款记录；费用未核实时仍显示缺。再次生成需重新确认费用。';if(job.submitted===false)return '回执确认尚未提交。处理报错原因后，可确认未提交后重试；批次仍需你确认继续。';return '先重新核对原作业和回执，必要时在平台人工核查。提交或费用状态不明时，请勿重复提交。';}
const known=v=>v===true?'已确认':v===false?'未发生':'缺 · 待核查';
function renderQueue(){
 if(S.queueComposing)return;
 const searchFocused=document.activeElement?.id==='queue-search',searchStart=document.activeElement?.selectionStart,searchEnd=document.activeElement?.selectionEnd;
 const batches=S.bridge?.batches||[],totals={pending:0,running:0,completed:0,review:0};
 for(const b of batches){for(const k of ['pending','running','completed'])totals[k]+=b.counts?.[k]||0;for(const k of ['failed','result_pending','login_required'])totals.review+=b.counts?.[k]||0;}
 $('nav-count').textContent=totals.running;
 $('queue-stats').innerHTML=Object.entries({pending:'本地排队',running:'运行中',completed:'已保存成品',review:'需要处理'}).map(([k,label])=>`<div class="stat-card"><span>${label}</span><strong>${S.bridge?totals[k]:'—'}</strong><small>全部批次中的任务数</small></div>`).join('');
 $('batch-list').innerHTML=batches.length?batches.map(b=>`<button class="batch-list-item ${b.batchId===S.batchId?'active':''}" data-batch="${esc(b.batchId)}"><strong>${esc(b.name)}</strong><span>${esc(LABEL[b.status]||b.status)} · ${Object.values(b.counts||{}).reduce((a,v)=>a+v,0)} 项</span><small>${b.counts?.completed||0} 成品 / ${b.counts?.running||0} 运行 / ${(b.counts?.failed||0)+(b.counts?.result_pending||0)+(b.counts?.login_required||0)} 待处理</small></button>`).join(''):'<div class="empty-state"><h3>尚无批次</h3><p>在准备创意中检查并保存本轮任务。</p></div>';
 const b=S.batch;
 if(!b){$('batch-detail').innerHTML='<div class="card empty-state"><h3>让创意有序发生</h3><p>选择一个已保存的批次，或先准备新的一轮创作。</p></div>';return;}
 const unresolved=b.items.filter(r=>['failed','result_pending','login_required'].includes(r.status)),pending=b.items.filter(r=>r.status==='pending'),online=!!S.bridge,done=b.items.filter(r=>r.status==='completed').length,visible=queueRows(b.items,S.queueFilter,S.queueSearch);
 const counts=Object.fromEntries(Object.keys(QUEUE_FILTERS).map(key=>[key,key==='all'?b.items.length:b.items.filter(row=>queueGroup(row)===key).length]));
 $('batch-detail').innerHTML=`${!online?'<div class="alert danger">服务离线，下方为上次状态。提交操作已停用。</div>':''}<div class="card batch-summary"><div class="card-title"><div><span class="eyebrow">${esc(LABEL[b.status]||b.status)}</span><h2>${esc(b.name)}</h2></div><span class="badge">${done} / ${b.items.length} 成品</span></div><p class="hint">${b.profileMode==='shared'?'共享档案 · 实际单路，跨批次由浏览器锁保护':'独立档案 · 最多 '+b.concurrency+' 路，需逐档案登录'} · 费用以真实回执为准</p>${b.pauseReason?`<div class="alert">${esc(b.pauseReason)}</div>`:''}<div class="toolbar">${['validated','paused'].includes(b.status)&&pending.length>0&&!unresolved.length?`<button class="button primary" data-batch-action="${b.status==='validated'?'start':'resume'}" ${!online?'disabled':''}>确认并${b.status==='validated'?'开始':'继续'}生成</button>`:''}${b.status==='running'?'<button class="button" data-batch-action="pause">暂停后续派发</button>':''}<button class="button" data-batch-action="recover" ${!online?'disabled':''}>重新核对回执</button><button class="button" data-batch-action="copy">输入复用到草稿</button>${!['completed','cancelled'].includes(b.status)?'<button class="text-button danger" data-batch-action="cancel">取消后续任务</button>':''}</div><p class="hint">${pending.length} 项等待派发。暂停或取消不会撤回已提交的任务。</p></div>
 <div class="card queue-controls"><div class="queue-search-row"><label for="queue-search">查找本批次任务</label><input id="queue-search" type="search" value="${esc(S.queueSearch)}" placeholder="搜索名称、提示词、作业号或报错" autocomplete="off"><button class="text-button" data-queue-clear>清除筛选</button></div><div class="queue-filters" role="group" aria-label="任务状态筛选">${Object.entries(QUEUE_FILTERS).map(([key,label])=>`<button class="button small ${S.queueFilter===key?'selected':''}" data-queue-filter="${key}" aria-pressed="${S.queueFilter===key}">${label} <span>${counts[key]}</span></button>`).join('')}</div><p class="hint" role="status">当前显示 ${visible.length} / ${b.items.length} 项 · 筛选仅改变显示，不影响派发顺序。</p></div>
 <div class="task-list">${visible.map(r=>{const job=r.liveJob||r.lastResult||{},phase=taskPhaseLabel(r,job),guidance=queueGuidance(r);return `<article class="card queue-task"><div class="card-title"><strong>${esc(r.name)}</strong><span class="badge ${queueGroup(r)==='attention'?'attention':r.status==='completed'?'success':''}">${esc(phase)}</span></div><p class="task-prompt">${esc(r.prompt)}</p><div class="task-meta"><span>${esc(r.aspect)} · ${esc(r.version)}</span><span>尝试 ${r.attempts||0}</span><span>提交：${known(job.submitted)}</span><span>费用：${job.actualPointDeduction!=null?esc(job.actualPointDeduction)+' 积分':job.billed===false?'未扣费':'缺'}</span></div>${r.failureReason?`<div class="alert">${esc(r.failureReason)}</div>`:''}${guidance?`<p class="task-guidance"><strong>下一步</strong>${esc(guidance)}</p>`:''}<div class="toolbar">${r.status==='completed'?`<button class="button small" data-item-action="images" data-item="${esc(r.id)}">查看成品</button>`:''}${r.status==='login_required'?`<button class="button small" data-item-action="login" data-item="${esc(r.id)}">打开人工登录窗口</button><button class="button small" data-item-action="login-check" data-item="${esc(r.id)}">核对登录</button>`:''}${['failed','result_pending','login_required'].includes(r.status)&&job.submitted===false?`<button class="button small" data-item-action="resubmit" data-item="${esc(r.id)}">确认未提交后重试</button>`:''}${['pending','failed','result_pending','login_required'].includes(r.status)?`<button class="text-button" data-item-action="skip" data-item="${esc(r.id)}">跳过后续处理</button>`:''}</div><details><summary>回执与诊断</summary><pre>${esc(JSON.stringify({jobId:r.currentJobId,phaseSource:job.phaseSource||'缺',result:job,history:r.attemptHistory||[]},null,2))}</pre></details></article>`;}).join('')}${!visible.length?'<div class="card empty-state"><h3>没有符合条件的任务</h3><p>换一个状态或清除搜索；原批次任务仍然保留。</p><button class="button" data-queue-clear>显示全部任务</button></div>':''}</div>`;
 if(searchFocused){const input=$('queue-search');input.focus();if(searchStart!=null)input.setSelectionRange(searchStart,searchEnd);}
}
function confirmAction(title,message,action,paid=false){dialog(title,`<p>${esc(message)}</p>${paid?'<div class="alert">本次动作可能产生费用。实际扣费金额：缺。请先核对任务和平台状态。</div><label class="checkbox-label"><input id="confirm-paid" type="checkbox">我明确授权本次提交可能产生的费用</label>':''}<div class="modal-actions"><button id="confirm-action" class="button ${paid?'primary':''}" ${paid?'disabled':''}>${paid?'授权并提交':'确认执行'}</button></div>`);if(paid)$('confirm-paid').onchange=()=>{$('confirm-action').disabled=!$('confirm-paid').checked||!S.bridge;};$('confirm-action').onclick=()=>guarded(async()=>{if(!S.bridge)throw Error('服务离线，请重新核对状态');await action();closeDialog();await refresh();});}
async function refresh(){if(S.refreshBusy)return;S.refreshBusy=true;try{const state=await api('/control/state');S.bridge=state;if(S.focusLatest){S.batchId=state.batches?.[0]?.batchId||'';S.batch=null;localStorage.setItem('multica-batch-v2',S.batchId);S.focusLatest=false;switchView('queue');}if(!state.batches?.some(b=>b.batchId===S.batchId)){S.batchId=state.batches?.[0]?.batchId||'';S.batch=null;localStorage.setItem('multica-batch-v2',S.batchId);}if(S.batchId)S.batch=await api('/control/batches/'+encodeURIComponent(S.batchId));await updateLoginAlerts(state);$('connection').textContent='本地服务已连接';$('connection').className='connection online';$('last-sync').textContent='同步于 '+new Date().toLocaleTimeString('zh-CN');}catch(e){S.bridge=null;$('connection').textContent='服务离线 · 草稿可编辑';$('connection').className='connection offline';$('last-sync').textContent='状态未同步，禁止重复提交';}finally{S.refreshBusy=false;$('check-batch').disabled=!S.draft.items.length||!S.bridge;const openDetails=[...document.querySelectorAll('#batch-detail details')].map(d=>d.open);renderQueue();document.querySelectorAll('#batch-detail details').forEach((d,i)=>d.open=!!openDetails[i]);if(S.view==='settings'&&!$('settings-content').contains(document.activeElement)){const expanded=$('settings-content').querySelector('details')?.open;renderSettings();if(expanded)$('settings-content').querySelector('details').open=true;}maybeShowLoginReminder();}}
const galleryFields=['gallery-search','gallery-filter','gallery-batch','gallery-tag','gallery-version','gallery-shape','gallery-sort'];
function galleryFilters(){return {search:$('gallery-search').value,status:$('gallery-filter').value,batch:$('gallery-batch').value,tag:$('gallery-tag').value,version:$('gallery-version').value,shape:$('gallery-shape').value,sort:$('gallery-sort').value,job:S.jobFilter};}
function saveGalleryFilters(){try{store('multica-gallery-v1',Object.fromEntries(galleryFields.map(k=>[k,$(k).value])));}catch{}}
function filterOptions(key,entries,label){const selected=$(key).value;$(key).innerHTML=`<option value="">${label}</option>`+entries.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('');if(selected&&!entries.some(([v])=>v===selected))$(key).innerHTML+=`<option value="${esc(selected)}">${esc(selected)}（暂无匹配）</option>`;$(key).value=selected;}
async function loadStorage(){S.storage=await api('/control/storage');if($('gallery-location'))$('gallery-location').textContent='原图默认位置：'+S.storage.outputDir+' · 素材副本：'+(S.storage.materialDir?S.storage.materialDir+'\\multica-assets':'尚未设置，可在连接与设置中配置');$('output-dir').placeholder='默认：'+S.storage.outputDir;}
async function loadAssets(){if(S.assetsBusy)return;S.assetsBusy=true;$('asset-grid').setAttribute('aria-busy','true');try{const data=await api('/control/assets');S.assets=data.items;filterOptions('gallery-batch',[...new Map(S.assets.filter(a=>a.batchId).map(a=>[a.batchId,a.batchName||a.batchId])).entries()],'全部批次');filterOptions('gallery-tag',[...new Set(S.assets.flatMap(a=>a.tags||[]))].sort().map(t=>[t,t]),'全部标签');filterOptions('gallery-version',[...new Set(S.assets.map(a=>a.version).filter(Boolean))].sort().map(v=>[v,v]),'全部版本');S.compare=new Set([...S.compare].filter(id=>S.assets.some(a=>a.id===id)));S.assetSelection=new Set([...S.assetSelection].filter(id=>S.assets.some(a=>a.id===id)));await loadStorage();renderAssets();}finally{S.assetsBusy=false;$('asset-grid').removeAttribute('aria-busy');}}
function filteredAssets(){return MulticaGallery.filter(S.assets,galleryFilters());}
function renderSelection(){const rows=filteredAssets();$('gallery-selection-count').textContent=S.assetSelection.size?'已选 '+S.assetSelection.size+' 张（跨筛选保留）':'未选择';$('gallery-reuse').disabled=!S.assetSelection.size;$('gallery-deliver').disabled=!S.assetSelection.size;$('gallery-select-all').checked=rows.length>0&&rows.every(a=>S.assetSelection.has(a.id));$('gallery-select-all').indeterminate=rows.some(a=>S.assetSelection.has(a.id))&&!$('gallery-select-all').checked;$('compare-count').textContent=S.compare.size;$('compare-button').disabled=S.compare.size<2;const chosen=[...S.compare].map(id=>S.assets.find(a=>a.id===id)).filter(Boolean);$('compare-tray').hidden=!chosen.length;$('compare-tray').innerHTML='<strong>比较托盘</strong>'+chosen.map(a=>`<div class="compare-chip"><img src="${imageURL(a)}" alt=""><span>${esc(a.name)}</span><button class="icon-button" data-remove-compare="${a.id}" aria-label="移出比较 ${esc(a.name)}">×</button></div>`).join('')+'<button class="text-button" data-clear-compare>清空比较</button>';}
function resetGallery(){for(const k of galleryFields)$(k).value=k==='gallery-filter'?'active':k==='gallery-sort'?'newest':'';S.jobFilter=null;saveGalleryFilters();renderAssets();}
function selectedAssets(){return S.assets.filter(a=>S.assetSelection.has(a.id));}
function reuseAssets(rows){const prepared=rows.map(a=>MulticaGallery.reuse(a));if(prepared.some(r=>r.missing.includes('提示词')))throw Error('所选图片缺少原始提示词，请取消选择后重试');const incomplete=prepared.filter(r=>r.missing.length);dialog('复用创意到草稿',`<p>将加入 ${rows.length} 项创意，保留已记录的请求参数。平台是否实际采用参数仍以原回执为准。</p>${incomplete.length?'<div class="alert">'+incomplete.map(r=>esc(r.item.name)+'：缺 '+esc(r.missing.join('、'))).join('<br>')+'</div><label class="checkbox-label"><input id="reuse-default-confirm" type="checkbox">缺失画幅 / 版本使用 16:9 / v8.2，缺失高级参数使用空参数；我会在提交前检查</label>':''}<div class="modal-actions"><button id="reuse-confirm" class="button primary" ${incomplete.length?'disabled':''}>加入草稿（不生成）</button></div>`);if(incomplete.length)$('reuse-default-confirm').onchange=e=>{$('reuse-confirm').disabled=!e.target.checked;};$('reuse-confirm').onclick=()=>guarded(async()=>{addItems(prepared.map(r=>({...r.item,id:id(),aspect:r.item.aspect||'16:9',version:r.item.version||'v8.2'})));closeDialog();switchView('prepare');toast('已加入 '+rows.length+' 项草稿；尚未提交生成');});}
async function deliverAssets(rows){await loadStorage();if(!S.storage.materialDir){switchView('settings');toast('请先填写素材目录；supent 对应位置由你指定。');return;}dialog('交付素材副本',`<p>将 ${rows.length} 张原图按原始字节复制到：</p><p class="metadata-prompt">${esc(S.storage.materialDir)}\\multica-assets</p><p class="hint">每张图附带来源 JSON。原图、任务和回执仍保留；同一图片再次交付会校验已有文件，冲突文件不会被覆盖。</p><div class="modal-actions"><button id="deliver-confirm" class="button primary">确认复制素材</button></div>`);$('deliver-confirm').onclick=()=>guarded(async()=>{const result=await api('/control/assets/deliver','POST',{ids:rows.map(a=>a.id)});dialog(result.ok?'素材交付已完成':'素材交付需要处理',`<p>目录：${esc(result.directory)}</p><ul>${result.items.map(i=>`<li>${esc(rows.find(a=>a.id===i.id)?.name)}：${i.ok?(i.status==='already_present'?'已有副本校验通过':'复制并校验通过'):esc(i.error)}</li>`).join('')}</ul><p class="hint">成功项附带来源清单，失败项可修正后重试。</p>`);});}
function imageURL(a){return '/control/assets/'+encodeURIComponent(a.id)+'/image';}
function renderAssets(){const rows=filteredAssets();$('asset-count').textContent=`${rows.length} / ${S.assets.length}`;$('compare-count').textContent=S.compare.size;$('compare-button').disabled=S.compare.size<2;renderSelection();$('asset-grid').innerHTML=(S.jobFilter?'<button class="button" id="clear-job-filter">清除作业筛选</button>':'')+(rows.length?rows.map(a=>`<article class="asset-card ${S.assetSelection.has(a.id)?'selected-asset':''}"><button class="asset-preview" data-preview="${a.id}" aria-label="预览 ${esc(a.name)}"><img src="${imageURL(a)}" alt="${esc(a.name)}" loading="lazy"></button><div class="asset-info"><div class="asset-title"><strong>${esc(a.name)}</strong><button class="icon-button ${a.favorite?'favorited':''}" data-favorite="${a.id}" aria-label="${a.favorite?'取消收藏':'收藏图片'}">${a.favorite?'★':'☆'}</button></div><p>${a.width&&a.height?a.width+' × '+a.height:'尺寸缺'} · ${esc(a.version||'版本缺')}</p><div class="asset-tags">${(a.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="asset-bottom"><label class="checkbox-label"><input type="checkbox" data-asset-select="${a.id}" ${S.assetSelection.has(a.id)?'checked':''}>选择</label><span>${esc(a.batchName||'历史作业')}</span><label class="checkbox-label"><input type="checkbox" data-compare="${a.id}" ${S.compare.has(a.id)?'checked':''}>比较</label></div></div></article>`).join(''):`<div class="card empty-state"><div class="empty-icon">▧</div><h3>这里等待你的好作品</h3><p>${S.assets.length?'没有图片匹配当前条件，请清空或调整筛选。':'暂无真实成品。完成生成并保存后，图片会出现在这里。'}</p></div>`);if($('clear-job-filter'))$('clear-job-filter').onclick=()=>{S.jobFilter=null;renderAssets();};}
async function patchAsset(asset,patch){const updated=await api('/control/assets/'+asset.id,'PATCH',patch);Object.assign(asset,updated);renderAssets();}
function previewAsset(assetId){const a=S.assets.find(a=>a.id===assetId);if(!a)return;S.previewId=a.id;const fields={作业编号:a.jobId,批次:a.batchName,尝试:a.attempt,回执编号:a.recordId,模型版本:a.version,请求画幅:a.requestedAspect,回执画幅:a.aspect&&typeof a.aspect==='object'?(a.aspect.applied||'缺'):a.aspect,尺寸:a.width&&a.height?a.width+' × '+a.height:null,参数: a.params?JSON.stringify(a.params):null,提交:known(a.submitted),扣费:known(a.billed),参数核验:a.parameterVerification==='transport_only'?'仅确认传入，平台采用待核验':'缺',文件:a.path,[a.sha256?.length===64?'回执 SHA256':'回执哈希（截短或缺）']:a.sha256};dialog(a.name,`<div class="preview-layout"><div class="preview-image"><img src="${imageURL(a)}" alt="${esc(a.name)}"><div class="toolbar"><button class="button small" id="preview-prev">← 上一张</button><button class="button small" id="preview-next">下一张 →</button><a class="button small" href="${imageURL(a)}?download=true" download>下载原图</a></div></div><div class="preview-details"><div class="toolbar"><button class="button" id="preview-favorite">${a.favorite?'★ 已收藏':'☆ 收藏'}</button><button class="button" id="preview-archive">${a.archived?'取消归档':'归档'}</button><button class="button" id="preview-open">定位文件</button><button class="button" id="preview-deliver">交付素材副本</button></div><label>标签（逗号分隔）<input id="preview-tags" value="${esc((a.tags||[]).join(', '))}"></label><button class="button small" id="preview-save-tags">保存标签</button><h3>创意提示词</h3><p class="metadata-prompt">${esc(a.prompt||'缺 · 历史作业未记录，无法完整复用')}</p><button class="button primary" id="reuse-asset" ${!a.prompt?'disabled':''}>复用到下一轮草稿 →</button><details><summary>实际发送文本</summary><p class="metadata-prompt">${esc(a.effectivePrompt||'缺')}</p></details><dl class="metadata">${Object.entries(fields).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v??'缺')}</dd>`).join('')}</dl><details><summary>完整真实回执</summary><pre>${esc(a.receipt?JSON.stringify(a.receipt,null,2):'缺')}</pre></details></div></div>`);$('modal').classList.add('preview-modal');S.previewId=a.id;
$('preview-favorite').onclick=()=>guarded(async()=>{await patchAsset(a,{favorite:!a.favorite});previewAsset(a.id);});$('preview-archive').onclick=()=>guarded(async()=>{await patchAsset(a,{archived:!a.archived});previewAsset(a.id);});$('preview-save-tags').onclick=()=>guarded(async()=>{await patchAsset(a,{tags:$('preview-tags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean)});toast('标签已保存到本机');});$('preview-deliver').onclick=()=>guarded(()=>deliverAssets([a]));$('preview-open').onclick=()=>guarded(()=>api('/control/assets/'+a.id+'/open','POST',{}));$('reuse-asset').onclick=()=>guarded(async()=>reuseAssets([a]));$('preview-prev').onclick=()=>navigatePreview(-1);$('preview-next').onclick=()=>navigatePreview(1);}
function navigatePreview(step){const rows=filteredAssets(),index=rows.findIndex(a=>a.id===S.previewId);if(rows.length)previewAsset(rows[(index+step+rows.length)%rows.length].id);}
function compareDialog(){const rows=[...S.compare].map(id=>S.assets.find(a=>a.id===id)).filter(Boolean);if(rows.length<2)return;const differences=MulticaGallery.differences(rows);const labels={prompt:'提示词',version:'模型版本',requestedAspect:'请求画幅',params:'高级参数'};dialog('并排比较 · '+rows.length+' 张',`<p class="hint">差异：${differences.length?differences.map(k=>labels[k]).join('、'):'已记录输入相同'}。点击图片可打开原图；缺失信息不代表平台采用默认值。</p><div class="compare-grid">${rows.map(a=>`<article><a href="${imageURL(a)}" target="_blank" rel="noopener" aria-label="打开原图 ${esc(a.name)}"><img src="${imageURL(a)}" alt="${esc(a.name)}"></a><h3>${esc(a.name)}</h3>${['version','requestedAspect','params','prompt'].map(k=>`<div class="compare-field ${differences.includes(k)?'has-difference':''}"><small>${labels[k]}</small><p class="metadata-prompt">${esc(k==='requestedAspect'?MulticaGallery.aspectOf(a)||'缺':k==='params'?a.params?JSON.stringify(a.params):'缺':a[k]||'缺')}</p></div>`).join('')}<div class="toolbar"><button class="button small" data-compare-favorite="${a.id}">${a.favorite?'★ 已收藏':'☆ 收藏'}</button><button class="button small" data-compare-reuse="${a.id}" ${!a.prompt?'disabled':''}>复用创意</button><button class="button small" data-preview="${a.id}">完整回溯</button></div></article>`).join('')}</div>`);$('modal').classList.add('preview-modal');$('modal-body').onclick=e=>{const preview=e.target.closest('[data-preview]'),fav=e.target.closest('[data-compare-favorite]'),reuse=e.target.closest('[data-compare-reuse]');if(preview)return previewAsset(preview.dataset.preview);if(fav)guarded(async()=>{const a=S.assets.find(a=>a.id===fav.dataset.compareFavorite);await patchAsset(a,{favorite:!a.favorite});compareDialog();});if(reuse)guarded(async()=>reuseAssets([S.assets.find(a=>a.id===reuse.dataset.compareReuse)]));};}
function renderSettings(){const h=S.bridge?.health;if(!h){$('settings-content').innerHTML='<div class="card empty-state"><h3>尚未连接本地服务</h3><p>请用 Windows 启动器启动工作台。草稿可继续编辑、导出。</p></div>';return;}$('settings-content').innerHTML=`<div class="card"><div class="card-title"><h2>本地创作环境</h2><span class="badge success">服务已连接</span></div><dl class="metadata">${Object.entries({版本:h.bridge||h.build||h.bridgeBuild||'缺',图片保存位置:h.outputDir||h.resultsDir||'缺',浏览器档案:h.profile||'缺',浏览器运行:S.bridge.browser?.running?'已打开':'未打开',自动看护进程:S.bridge.watchdog?.processRunning==null?'缺':S.bridge.watchdog.processRunning?'运行中':'未运行'}).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p>共享档案可靠单路运行；独立档案最多三路，分别登录。真实平台并发和高级参数采用情况尚待授权验证。</p><div class="toolbar"><button class="button" data-setting="browser/start">打开人工登录窗口</button><button class="button" data-setting="browser/stop">关闭登录窗口</button></div></div><div class="card"><h2>图片保存与素材位置</h2><p class="hint">原图保存位置供新批次使用；批次可单独指定目录，既有批次和历史图片位置保持原记录。素材目录保存你选中的原图副本与来源清单。</p><label>默认原图保存位置<input id="storage-output" value="${esc(S.storage?.outputDir||h.outputDir||'')}"></label><label>素材目录（可填 supent 项目对应的本地素材位置）<input id="storage-material" value="${esc(S.storage?.materialDir||'')}" placeholder="例如 D:\创作项目\素材"></label><p class="hint">交付文件位于所填目录的 multica-assets 子目录。supent 的具体位置尚未确认；此功能执行本地复制，不代表远程上传或正式导入。</p><button class="button primary" id="save-storage">保存位置设置</button></div><div class="card"><h2>人工登录提醒</h2><label class="checkbox-label"><input id="login-reminder-enabled" type="checkbox" ${S.loginReminder?'checked':''}>检测未登录时弹窗呼唤人工处理</label><p class="hint">默认开启，设置保存在当前浏览器。工作台保持打开时生效；后台标签页可能延迟，不会强制切到前台。同一次未登录事件关闭后不重复弹窗，其他编辑和确认窗口关闭后再提醒。</p><div class="toolbar"><span>${S.loginAlerts.length} 项待登录处理</span><button class="button" data-login-reminder-review ${!S.loginAlerts.length?'disabled':''}>查看登录提醒</button></div></div><details class="card"><summary>技术诊断与历史回执</summary><p class="hint">只读取真实数据。未知字段保持为缺。</p><pre>${esc(JSON.stringify({health:h,scheduler:S.bridge.batchScheduler,watchdog:S.bridge.watchdog},null,2))}</pre><h3>最近作业</h3><pre>${esc(JSON.stringify(S.bridge.jobs,null,2))}</pre><h3>最近回执</h3><pre>${esc(JSON.stringify(S.bridge.receipts,null,2))}</pre></details>`;}
$('default-aspect').innerHTML=options(ASPECTS,'16:9');$('default-version').innerHTML=options(VERSIONS,'v8.2');
for(const [el,k] of [['batch-name','name'],['output-dir','outputDir'],['profile-mode','profileMode'],['concurrency','concurrency']]){$(el).value=S.draft[k];$(el).onchange=()=>{S.draft[k]=k==='concurrency'?Number($(el).value):$(el).value;persist();};}
const composerIds=['prompt-input','task-name','default-aspect','default-version','param-stylize','param-chaos','param-seed','param-quality','param-raw'];
const c=readStored('multica-composer-v2',null,c=>c&&typeof c==='object'&&!Array.isArray(c));if(c){for(const key of composerIds)if(c[key]!=null){if(key==='param-raw')$(key).checked=!!c[key];else $(key).value=c[key];}if(c.prompt)$('prompt-input').value=c.prompt;if(c.name)$('task-name').value=c.name;}
for(const key of composerIds)$(key).addEventListener('input',()=>{try{store('multica-composer-v2',Object.fromEntries(composerIds.map(k=>[k,k==='param-raw'?$(k).checked:$(k).value])));}catch{toast('草稿自动保存不可用，请导出备份。');}});
$('add-task').onclick=()=>guarded(async()=>{const prompt=$('prompt-input').value.trim();if(!prompt)throw Error('先写下一条创意');addItems([{id:id(),name:$('task-name').value.trim()||'创意 '+(S.draft.items.length+1),prompt,aspect:$('default-aspect').value,version:$('default-version').value,params:paramsFrom()}]);$('prompt-input').value='';$('task-name').value='';localStorage.removeItem('multica-composer-v2');toast('已加入草稿，尚未提交。');});
$('draft-table').onchange=e=>{const tr=e.target.closest('[data-id]'),r=S.draft.items.find(r=>r.id===tr?.dataset.id),key=e.target.dataset.edit;if(!r||!key)return;if(key==='selected'){if(e.target.checked)S.selected.add(r.id);else S.selected.delete(r.id);renderDraft();}else{r[key]=e.target.value;persist();}};
$('draft-table').oninput=e=>{const tr=e.target.closest('[data-id]'),r=S.draft.items.find(r=>r.id===tr?.dataset.id);if(r&&['name','prompt'].includes(e.target.dataset.edit)){r[e.target.dataset.edit]=e.target.value;persist();}};
$('draft-table').onclick=e=>{const button=e.target.closest('[data-row]');if(!button)return;const r=S.draft.items.find(r=>r.id===button.closest('[data-id]').dataset.id);if(button.dataset.row==='params')openParams([r.id]);if(button.dataset.row==='copy')guarded(async()=>addItems([{...copyItem(r),name:r.name+' · 副本'}]));if(button.dataset.row==='remove'){S.draft.items=S.draft.items.filter(a=>a.id!==r.id);S.selected.delete(r.id);persist();renderDraft();}};
$('select-all').onchange=e=>{S.selected=e.target.checked?new Set(S.draft.items.map(r=>r.id)):new Set();renderDraft();};
$('bulk-bar').onclick=e=>{const b=e.target.closest('[data-bulk]');if(!b)return;const rows=S.draft.items.filter(r=>S.selected.has(r.id));if(b.dataset.bulk==='settings')openParams(rows.map(r=>r.id));if(b.dataset.bulk==='duplicate')guarded(async()=>addItems(rows.map(r=>({...copyItem(r),name:r.name+' · 副本'}))));if(b.dataset.bulk==='delete'){S.draft.items=S.draft.items.filter(r=>!S.selected.has(r.id));S.selected.clear();persist();renderDraft();}};
$('experiment-button').onclick=experimentDialog;$('import-button').onclick=importDialog;$('import-batch').onclick=importDialog;$('templates-button').onclick=templatesDialog;
$('save-template').onclick=()=>{if(!S.draft.items.length)return toast('请先加入任务');dialog('保存创作模板','<label>模板名称<input id="template-name" placeholder="例如：人物风格探索"></label><div class="modal-actions"><button class="button primary" id="apply-template">保存模板</button></div>');$('apply-template').onclick=()=>guarded(async()=>{const name=$('template-name').value.trim();if(!name)throw Error('请填写模板名称');const next=[{name,items:S.draft.items.map(copyItem)},...S.templates].slice(0,30);store('multica-templates-v2',next);S.templates=next;closeDialog();toast('模板已保存到当前浏览器');});};
$('export-draft').onclick=()=>exportJSON(S.draft,'multica-draft');$('export-assets').onclick=()=>exportJSON({exportedAt:new Date().toISOString(),items:filteredAssets()},'multica-assets');$('check-batch').onclick=()=>guarded(checkBatch);
$('new-draft').onclick=()=>{dialog('新建草稿',`<p>当前草稿有 ${S.draft.items.length} 项。可先导出备份，再清空草稿；已保存批次和图片不受影响。</p><div class="modal-actions"><button id="backup-draft" class="button">先导出当前草稿</button><button id="clear-draft" class="button primary">清空并新建</button></div>`);$('backup-draft').onclick=()=>exportJSON(S.draft,'multica-draft');$('clear-draft').onclick=()=>{S.draft=emptyDraft();S.selected.clear();$('batch-name').value='';$('output-dir').value='';$('profile-mode').value=S.draft.profileMode;$('concurrency').value=S.draft.concurrency;persist();renderDraft();closeDialog();switchView('prepare');};};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{S.jobFilter=null;switchView(b.dataset.view);});
$('batch-list').onclick=e=>{const b=e.target.closest('[data-batch]');if(b)guarded(async()=>{S.batchId=b.dataset.batch;S.queueFilter='all';S.queueSearch='';localStorage.setItem('multica-batch-v2',S.batchId);await refresh();});};
$('batch-detail').oncompositionstart=e=>{if(e.target.id==='queue-search')S.queueComposing=true;};
$('batch-detail').oncompositionend=e=>{if(e.target.id!=='queue-search')return;S.queueComposing=false;S.queueSearch=e.target.value;renderQueue();};
$('batch-detail').oninput=e=>{if(e.target.id!=='queue-search'||e.isComposing||S.queueComposing)return;S.queueSearch=e.target.value;renderQueue();};
$('batch-detail').onclick=e=>{const filter=e.target.closest('[data-queue-filter]'),clear=e.target.closest('[data-queue-clear]');if(filter||clear){S.queueFilter=filter?filter.dataset.queueFilter:'all';if(clear)S.queueSearch='';renderQueue();return;}const action=e.target.closest('[data-batch-action]'),itemAction=e.target.closest('[data-item-action]'),b=S.batch;if(!b)return;const base='/control/batches/'+encodeURIComponent(b.batchId);if(action){const a=action.dataset.batchAction;if(a==='copy')return guarded(async()=>{addItems(b.items.map(copyItem));switchView('prepare');toast('已复用批次输入，未携带授权或运行状态');});if(['start','resume'].includes(a))return confirmAction('确认本次付费生成',`批次「${b.name}」，将派发尚未提交的任务。请核对 ${b.items.length} 项输入与浏览器登录状态。`,()=>api(base+'/'+a,'POST',{paid_confirmed:true}),true);if(a==='cancel')return confirmAction('取消后续任务','已提交任务继续等待回执，不会撤销或退费。',()=>api(base+'/cancel','POST',{}));return guarded(async()=>{await api(base+'/'+a,'POST',{});await refresh();});}if(itemAction){const row=b.items.find(r=>r.id===itemAction.dataset.item),a=itemAction.dataset.itemAction,itemBase=base+'/items/'+encodeURIComponent(row.id);if(a==='images'){S.jobFilter=row.currentJobId;switchView('gallery');return;}if(a==='skip')return confirmAction('跳过此任务的后续处理','已有作业、回执与成品仍保留；已提交任务不会被撤回。',()=>api(itemBase+'/skip','POST',{}));if(a==='resubmit')return confirmAction('确认本次重新提交',`「${row.name}」的回执明确记录未提交。准备新尝试后，批次保持暂停，需要继续批次才会派发。`,()=>api(itemBase+'/resubmit','POST',{paid_confirmed:true,confirm_repeat_charge:true}),true);guarded(async()=>{const result=await api(itemBase+'/login',a==='login'?'POST':'GET',a==='login'?{}:undefined);toast(result.message||(loginSnapshotReady(result)?'登录已核验':'尚未核验到登录，请在窗口中手动完成'));await refresh();});}};
$('asset-grid').onclick=e=>{const preview=e.target.closest('[data-preview]'),fav=e.target.closest('[data-favorite]');if(preview)previewAsset(preview.dataset.preview);if(fav)guarded(async()=>{const a=S.assets.find(a=>a.id===fav.dataset.favorite);await patchAsset(a,{favorite:!a.favorite});});};
$('asset-grid').onchange=e=>{const key=e.target.dataset.compare||e.target.dataset.assetSelect;if(!key)return;const collection=e.target.dataset.compare?S.compare:S.assetSelection,limit=e.target.dataset.compare?4:100;if(e.target.checked&&collection.size>=limit){e.target.checked=false;return toast('最多选择 '+limit+' 张图片');}if(e.target.checked)collection.add(key);else collection.delete(key);renderAssets();};
$('compare-tray').onclick=e=>{const remove=e.target.closest('[data-remove-compare]');if(remove)S.compare.delete(remove.dataset.removeCompare);if(e.target.closest('[data-clear-compare]'))S.compare.clear();renderAssets();};
$('gallery-select-all').onchange=e=>{const rows=filteredAssets();if(e.target.checked){const union=new Set([...S.assetSelection,...rows.map(a=>a.id)]);if(union.size>100){e.target.checked=false;return toast('当前结果与已有选择超过 100 张，请缩小筛选范围。');}S.assetSelection=union;}else for(const a of rows)S.assetSelection.delete(a.id);renderAssets();};
$('gallery-selection-clear').onclick=()=>{S.assetSelection.clear();renderAssets();};
$('gallery-reuse').onclick=()=>guarded(async()=>reuseAssets(selectedAssets()));$('gallery-deliver').onclick=()=>guarded(()=>deliverAssets(selectedAssets()));
$('gallery-reset').onclick=resetGallery;$('compare-button').onclick=compareDialog;
const storedGallery=readStored('multica-gallery-v1',{},v=>v&&typeof v==='object'&&!Array.isArray(v));
for(const key of galleryFields){if(typeof storedGallery[key]==='string'){if($(key).tagName==='SELECT'&&!Array.from($(key).options).some(o=>o.value===storedGallery[key]))$(key).insertAdjacentHTML('beforeend',`<option value="${esc(storedGallery[key])}">${esc(storedGallery[key])}</option>`);$(key).value=storedGallery[key];}$(key).addEventListener(key==='gallery-search'?'input':'change',e=>{if(e.isComposing)return;saveGalleryFilters();renderAssets();});}
$('gallery-search').addEventListener('compositionend',()=>{saveGalleryFilters();renderAssets();});
$('settings-content').onchange=e=>{if(e.target.id!=='login-reminder-enabled')return;try{store('multica-login-reminder-v1',e.target.checked);S.loginReminder=e.target.checked;toast(S.loginReminder?'人工登录弹窗提醒已开启':'已关闭自动弹窗，任务中的人工登录入口仍可用');if(S.loginReminder)maybeShowLoginReminder(true);}catch{e.target.checked=S.loginReminder;toast('设置未保存，请检查浏览器存储。');}};
$('settings-content').onclick=e=>{if(e.target.closest('#save-storage'))return guarded(async()=>{S.storage=await api('/control/storage','PATCH',{outputDir:$('storage-output').value.trim(),materialDir:$('storage-material').value.trim()});renderSettings();toast('位置已保存。新批次默认使用此原图目录；既有文件未移动。');});if(e.target.closest('[data-login-reminder-review]'))return maybeShowLoginReminder(true);const b=e.target.closest('[data-setting]');if(b)guarded(async()=>{const r=await api('/control/'+b.dataset.setting,'POST',{});toast(r.message||'操作已完成');await refresh();});};
for(const key of ['refresh-button','queue-refresh'])$(key).onclick=()=>guarded(refresh);$('gallery-refresh').onclick=()=>guarded(loadAssets);$('modal-close').onclick=closeDialog;$('modal').addEventListener('close',()=>{S.previewId=null;$('modal-body').onclick=null;setTimeout(maybeShowLoginReminder,0);});
$('help-button').onclick=()=>dialog('开始你的第一轮创作','<ol><li>准备创意：加入任务，批量调整或导入。草稿自动保存在当前浏览器，可导出迁移。</li><li>检查并保存：检查参数和重复输入，保存不生成。</li><li>运行与批次：人工完成平台登录后，明确授权本次付费提交。</li><li>图片工作区：预览、收藏、标签、比较，复用已记录的提示词与参数。</li></ol><p>状态不明时，先核对回执。不要新建同样任务来绕过待核查状态。</p><p class="hint">Alt + 1–4 切换空间；Ctrl + Enter 检查草稿；预览时 ← / → 切图；Esc 关闭对话框。</p>');
$('modal').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...$('modal').querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary,[tabindex="0"]')].filter(el=>el.getClientRects().length&&!el.closest('[hidden]'));if(!items.length)return;const index=items.indexOf(document.activeElement);e.preventDefault();items[(index+(e.shiftKey?-1:1)+items.length)%items.length].focus();});
document.addEventListener('keydown',e=>{if(!$('modal').open&&e.altKey&&['1','2','3','4'].includes(e.key)){e.preventDefault();switchView(['prepare','queue','gallery','settings'][Number(e.key)-1]);}if(e.ctrlKey&&e.key==='Enter'&&S.view==='prepare'&&!$('modal').open){e.preventDefault();guarded(checkBatch);}if(S.previewId&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();navigatePreview(e.key==='ArrowLeft'?-1:1);}});
window.MulticaWorkbench={openLatestBatch:()=>{S.focusLatest=true;switchView('queue');return refresh();}};
renderDraft();if(storageNotice)toast(storageNotice);refresh();setInterval(()=>{if(!S.busy)refresh();},5000);
